Aim shooter
team20/Robot2024 pull request #50
Opened 2024-02-27 16:32 UTC by IvyCactus

2024-02-27 16:44 UTC, Gold856 requested changes

2024-02-27 16:44 UTC, Gold856 commented on Robot2024
Remove.

2024-02-27 17:03 UTC, NatalieEMann approved these changes

2024-02-27 17:03 UTC, NatalieEMann commented on src/main/java/frc/robot/commands/aimshooter/AimHeightCommand.java
> +				break;
you can put the breaks at the end...not necessary though.

2024-02-27 20:05 UTC, Gold856 requested changes
Adjust operations are completely broken, either fix them or remove them

2024-02-27 20:26 UTC, IvyCactus commented
> Adjust operations are completely broken, either fix them or remove them

I removed it from the command and commented it from the subsystem, keeping it around in some form in case we ever need it -- whatever that may be

2024-02-27 20:27 UTC, Gold856 requested changes

2024-02-27 20:27 UTC, Gold856 commented on src/main/java/frc/robot/Targeter.java
> +// imports
Remove

2024-02-27 20:27 UTC, Gold856 commented on src/main/java/frc/robot/Targeter.java
> +
Remove

2024-02-27 20:27 UTC, Gold856 commented on src/main/java/frc/robot/Targeter.java
Remove extra targeters, we can come back to them later

2024-02-27 20:35 UTC, Gold856 requested changes

2024-02-27 20:35 UTC, Gold856 commented on src/main/java/frc/robot/Constants.java
> +		public static final double aimerLength = .25; // TODO change to deltaX between edge of robot and aimer axis
Rename to start with `k`

2024-02-28 01:11 UTC, IvyCactus commented on src/main/java/frc/robot/Targeter.java
There is no reason to remove that code, it doesn't help anything and only raises the probability of us being mildly annoyed in the future

2024-02-28 01:15 UTC, IvyCactus commented on src/main/java/frc/robot/Targeter.java
> +
Yeah

2024-02-28 03:12 UTC, Gold856 approved these changes

2024-02-28 03:13 UTC, merged